version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: note-app-php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: postgres:13
    container_name: note-app-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: note_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  node:
    image: node:18
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - laravel

networks:
  laravel:

volumes:
  pgdata:
